language: go

os:
  - linux
  - osx

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - if [[ $TRAVIS_GO_VERSION == 1.13* ]]; then go get github.com/axw/gocov/gocov github.com/modocache/gover github.com/mattn/goveralls; fi

script:
  - go test -v -tags ci ./...
  - if [[ $TRAVIS_GO_VERSION == 1.13* ]]; then go test -tags ci -race -covermode atomic -coverprofile=profile.cov ./...; fi
  - if [[ $TRAVIS_GO_VERSION == 1.13* ]]; then $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci; fi

notifications:
  email:
    on_success: change
    on_failure: always
